// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WSBaseReqProto.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求实体 type (0: 心跳, 1: 登录)
type WSBaseReqProto struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Sid                  string   `protobuf:"bytes,3,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WSBaseReqProto) Reset()         { *m = WSBaseReqProto{} }
func (m *WSBaseReqProto) String() string { return proto.CompactTextString(m) }
func (*WSBaseReqProto) ProtoMessage()    {}
func (*WSBaseReqProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfc576e6c81ba50, []int{0}
}

func (m *WSBaseReqProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WSBaseReqProto.Unmarshal(m, b)
}
func (m *WSBaseReqProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WSBaseReqProto.Marshal(b, m, deterministic)
}
func (m *WSBaseReqProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WSBaseReqProto.Merge(m, src)
}
func (m *WSBaseReqProto) XXX_Size() int {
	return xxx_messageInfo_WSBaseReqProto.Size(m)
}
func (m *WSBaseReqProto) XXX_DiscardUnknown() {
	xxx_messageInfo_WSBaseReqProto.DiscardUnknown(m)
}

var xxx_messageInfo_WSBaseReqProto proto.InternalMessageInfo

func (m *WSBaseReqProto) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *WSBaseReqProto) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *WSBaseReqProto) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func init() {
	proto.RegisterType((*WSBaseReqProto)(nil), "protocol.WSBaseReqProto")
}

func init() {
	proto.RegisterFile("WSBaseReqProto.proto", fileDescriptor_1dfc576e6c81ba50)
}

var fileDescriptor_1dfc576e6c81ba50 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x09, 0x0f, 0x76, 0x4a,
	0x2c, 0x4e, 0x0d, 0x4a, 0x2d, 0x0c, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2b, 0x00, 0x91, 0x42, 0x1c,
	0x60, 0x2a, 0x39, 0x3f, 0x47, 0xc9, 0x83, 0x8b, 0x0f, 0x55, 0x85, 0x90, 0x10, 0x17, 0x4b, 0x49,
	0x65, 0x41, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0x5c,
	0x9a, 0x99, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x12, 0x04, 0x62, 0x82, 0x44, 0x8a, 0x33, 0x53,
	0x24, 0x98, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x27, 0x26, 0x0f, 0xc6, 0x24, 0x36, 0xb0,
	0xb9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0xa3, 0x62, 0x7b, 0x76, 0x00, 0x00, 0x00,
}
