// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WSBaseResProto.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 返回实体
type WSBaseResProto struct {
	Type                 int32              `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Message              *WSMessageResProto `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User                 *WSUserResProto    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	CreateTime           string             `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WSBaseResProto) Reset()         { *m = WSBaseResProto{} }
func (m *WSBaseResProto) String() string { return proto.CompactTextString(m) }
func (*WSBaseResProto) ProtoMessage()    {}
func (*WSBaseResProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_e302bcd2ce9b4b07, []int{0}
}

func (m *WSBaseResProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WSBaseResProto.Unmarshal(m, b)
}
func (m *WSBaseResProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WSBaseResProto.Marshal(b, m, deterministic)
}
func (m *WSBaseResProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WSBaseResProto.Merge(m, src)
}
func (m *WSBaseResProto) XXX_Size() int {
	return xxx_messageInfo_WSBaseResProto.Size(m)
}
func (m *WSBaseResProto) XXX_DiscardUnknown() {
	xxx_messageInfo_WSBaseResProto.DiscardUnknown(m)
}

var xxx_messageInfo_WSBaseResProto proto.InternalMessageInfo

func (m *WSBaseResProto) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *WSBaseResProto) GetMessage() *WSMessageResProto {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *WSBaseResProto) GetUser() *WSUserResProto {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *WSBaseResProto) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*WSBaseResProto)(nil), "protocol.WSBaseResProto")
}

func init() {
	proto.RegisterFile("WSBaseResProto.proto", fileDescriptor_e302bcd2ce9b4b07)
}

var fileDescriptor_e302bcd2ce9b4b07 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x09, 0x0f, 0x76, 0x4a,
	0x2c, 0x4e, 0x0d, 0x4a, 0x2d, 0x0e, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2b, 0x00, 0x91, 0x42, 0x1c,
	0x60, 0x2a, 0x39, 0x3f, 0x47, 0x4a, 0x3c, 0x3c, 0xd8, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x1d, 0x4d,
	0x89, 0x94, 0x48, 0x78, 0x70, 0x68, 0x71, 0x6a, 0x11, 0xaa, 0xa8, 0xd2, 0x2a, 0x46, 0x2e, 0x3e,
	0x54, 0x13, 0x85, 0x84, 0xb8, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58,
	0x83, 0xc0, 0x6c, 0x21, 0x53, 0x2e, 0xf6, 0x5c, 0x88, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc,
	0x46, 0xd2, 0x7a, 0x30, 0x1b, 0xf5, 0x30, 0x2c, 0x0c, 0x82, 0xa9, 0x15, 0xd2, 0xe1, 0x62, 0x29,
	0x2d, 0x4e, 0x2d, 0x92, 0x60, 0x06, 0xeb, 0x91, 0x40, 0xd6, 0x83, 0xec, 0x96, 0x20, 0xb0, 0x2a,
	0x21, 0x79, 0x2e, 0xee, 0xe4, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0xf8, 0x92, 0xcc, 0xdc, 0x54, 0x09,
	0x16, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x2e, 0x88, 0x50, 0x48, 0x66, 0x6e, 0xaa, 0x13, 0x93, 0x07,
	0x63, 0x12, 0x1b, 0xd8, 0x0c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xcc, 0x24, 0xa0,
	0x08, 0x01, 0x00, 0x00,
}
