// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WSMessageResProto.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求实体
type WSMessageResProto struct {
	ReceiveId            uint64   `protobuf:"varint,1,opt,name=receive_id,json=receiveId,proto3" json:"receive_id,omitempty"`
	MsgType              int32    `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgContent           string   `protobuf:"bytes,3,opt,name=msg_content,json=msgContent,proto3" json:"msg_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WSMessageResProto) Reset()         { *m = WSMessageResProto{} }
func (m *WSMessageResProto) String() string { return proto.CompactTextString(m) }
func (*WSMessageResProto) ProtoMessage()    {}
func (*WSMessageResProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe76d099c93fb4e8, []int{0}
}

func (m *WSMessageResProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WSMessageResProto.Unmarshal(m, b)
}
func (m *WSMessageResProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WSMessageResProto.Marshal(b, m, deterministic)
}
func (m *WSMessageResProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WSMessageResProto.Merge(m, src)
}
func (m *WSMessageResProto) XXX_Size() int {
	return xxx_messageInfo_WSMessageResProto.Size(m)
}
func (m *WSMessageResProto) XXX_DiscardUnknown() {
	xxx_messageInfo_WSMessageResProto.DiscardUnknown(m)
}

var xxx_messageInfo_WSMessageResProto proto.InternalMessageInfo

func (m *WSMessageResProto) GetReceiveId() uint64 {
	if m != nil {
		return m.ReceiveId
	}
	return 0
}

func (m *WSMessageResProto) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *WSMessageResProto) GetMsgContent() string {
	if m != nil {
		return m.MsgContent
	}
	return ""
}

func init() {
	proto.RegisterType((*WSMessageResProto)(nil), "protocol.WSMessageResProto")
}

func init() {
	proto.RegisterFile("WSMessageResProto.proto", fileDescriptor_fe76d099c93fb4e8)
}

var fileDescriptor_fe76d099c93fb4e8 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0f, 0x0f, 0xf6, 0x4d,
	0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x0d, 0x4a, 0x2d, 0x0e, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2b, 0x00,
	0x91, 0x42, 0x1c, 0x60, 0x2a, 0x39, 0x3f, 0x47, 0x29, 0x8f, 0x4b, 0x10, 0x43, 0x91, 0x90, 0x2c,
	0x17, 0x57, 0x51, 0x6a, 0x72, 0x6a, 0x66, 0x59, 0x6a, 0x7c, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x4b, 0x10, 0x27, 0x54, 0xc4, 0x33, 0x45, 0x48, 0x92, 0x8b, 0x23, 0xb7, 0x38, 0x3d, 0xbe,
	0xa4, 0xb2, 0x20, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x88, 0x3d, 0xb7, 0x38, 0x3d, 0xa4,
	0xb2, 0x20, 0x55, 0x48, 0x9e, 0x8b, 0x1b, 0x24, 0x95, 0x9c, 0x9f, 0x57, 0x92, 0x9a, 0x57, 0x22,
	0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x95, 0x5b, 0x9c, 0xee, 0x0c, 0x11, 0x71, 0x62, 0xf2,
	0x60, 0x4c, 0x62, 0x03, 0xdb, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x16, 0x7f, 0x12, 0x8c,
	0x9f, 0x00, 0x00, 0x00,
}
